#!/bin/bash

iIFS=$IFS
IFS='=&'
qs=($QUERY_STRING)
IFS=$iIFS

declare -A params
for ((i=0; i<${#qs[@]}; i+=2))
do
    params[${qs[i]}]=${qs[i+1]}
done

function price {
    RANDOM=$1
    echo $(($RANDOM % ($3 - $2 + 1) + $2))
}

function seed {
    echo $(($(date +%s) / 2 - $1))
}

printf "Content-type: text/plain\n\n"

if [ "${params[type]}" = "history" ]; then
    for (( i=1; i <= 60; i++ )) do
        printf "%s " "$(price $(seed $i) 30000 16000000)"
    done
    printf "\n"
    echo $(price $(seed 61) 30000 16000000)
else
    SEED=$(($(date +%s) / 2))
    echo $(price $(seed 0) 30000 16000000)
fi