idxToKeyName = {}
idxToKeyName[0x00] = "UNKNOWN"
idxToKeyName[0x01] = "DIK_ESCAPE"
idxToKeyName[0x02] = "DIK_1"
idxToKeyName[0x03] = "DIK_2"
idxToKeyName[0x04] = "DIK_3"
idxToKeyName[0x05] = "DIK_4"
idxToKeyName[0x06] = "DIK_5"
idxToKeyName[0x07] = "DIK_6"
idxToKeyName[0x08] = "DIK_7"
idxToKeyName[0x09] = "DIK_8"
idxToKeyName[0x0A] = "DIK_9"
idxToKeyName[0x0B] = "DIK_0"
idxToKeyName[0x0C] = "DIK_MINUS"
idxToKeyName[0x0D] = "DIK_EQUALS"
idxToKeyName[0x0E] = "DIK_BACK"
idxToKeyName[0x0F] = "DIK_TAB"
idxToKeyName[0x10] = "DIK_Q"
idxToKeyName[0x11] = "DIK_W"
idxToKeyName[0x12] = "DIK_E"
idxToKeyName[0x13] = "DIK_R"
idxToKeyName[0x14] = "DIK_T"
idxToKeyName[0x15] = "DIK_Y"
idxToKeyName[0x16] = "DIK_U"
idxToKeyName[0x17] = "DIK_I"
idxToKeyName[0x18] = "DIK_O"
idxToKeyName[0x19] = "DIK_P"
idxToKeyName[0x1A] = "DIK_LBRACKET"
idxToKeyName[0x1B] = "DIK_RBRACKET"
idxToKeyName[0x1C] = "DIK_RETURN"
idxToKeyName[0x1D] = "DIK_LCONTROL"
idxToKeyName[0x1E] = "DIK_A"
idxToKeyName[0x1F] = "DIK_S"
idxToKeyName[0x20] = "DIK_D"
idxToKeyName[0x21] = "DIK_F"
idxToKeyName[0x22] = "DIK_G"
idxToKeyName[0x23] = "DIK_H"
idxToKeyName[0x24] = "DIK_J"
idxToKeyName[0x25] = "DIK_K"
idxToKeyName[0x26] = "DIK_L"
idxToKeyName[0x27] = "DIK_SEMICOLON"
idxToKeyName[0x28] = "DIK_APOSTROPHE"
idxToKeyName[0x29] = "DIK_GRAVE"
idxToKeyName[0x2A] = "DIK_LSHIFT"
idxToKeyName[0x2B] = "DIK_BACKSLASH"
idxToKeyName[0x2C] = "DIK_Z"
idxToKeyName[0x2D] = "DIK_X"
idxToKeyName[0x2E] = "DIK_C"
idxToKeyName[0x2F] = "DIK_V"
idxToKeyName[0x30] = "DIK_B"
idxToKeyName[0x31] = "DIK_N"
idxToKeyName[0x32] = "DIK_M"
idxToKeyName[0x33] = "DIK_COMMA"
idxToKeyName[0x34] = "DIK_PERIOD"
idxToKeyName[0x35] = "DIK_SLASH"
idxToKeyName[0x36] = "DIK_RSHIFT"
idxToKeyName[0x37] = "DIK_MULTIPLY"
idxToKeyName[0x38] = "DIK_LMENU"
idxToKeyName[0x39] = "DIK_SPACE"
idxToKeyName[0x3A] = "DIK_CAPITAL"
idxToKeyName[0x3B] = "DIK_F1"
idxToKeyName[0x3C] = "DIK_F2"
idxToKeyName[0x3D] = "DIK_F3"
idxToKeyName[0x3E] = "DIK_F4"
idxToKeyName[0x3F] = "DIK_F5"
idxToKeyName[0x40] = "DIK_F6"
idxToKeyName[0x41] = "DIK_F7"
idxToKeyName[0x42] = "DIK_F8"
idxToKeyName[0x43] = "DIK_F9"
idxToKeyName[0x44] = "DIK_F10"
idxToKeyName[0x45] = "DIK_NUMLOCK"
idxToKeyName[0x46] = "DIK_SCROLL"
idxToKeyName[0x47] = "DIK_NUMPAD7"
idxToKeyName[0x48] = "DIK_NUMPAD8"
idxToKeyName[0x49] = "DIK_NUMPAD9"
idxToKeyName[0x4A] = "DIK_SUBTRACT"
idxToKeyName[0x4B] = "DIK_NUMPAD4"
idxToKeyName[0x4C] = "DIK_NUMPAD5"
idxToKeyName[0x4D] = "DIK_NUMPAD6"
idxToKeyName[0x4E] = "DIK_ADD"
idxToKeyName[0x4F] = "DIK_NUMPAD1"
idxToKeyName[0x50] = "DIK_NUMPAD2"
idxToKeyName[0x51] = "DIK_NUMPAD3"
idxToKeyName[0x52] = "DIK_NUMPAD0"
idxToKeyName[0x53] = "DIK_DECIMAL"
idxToKeyName[0x56] = "DIK_OEM_102"
idxToKeyName[0x57] = "DIK_F11"
idxToKeyName[0x58] = "DIK_F12"
idxToKeyName[0x64] = "DIK_F13"
idxToKeyName[0x65] = "DIK_F14"
idxToKeyName[0x66] = "DIK_F15"
idxToKeyName[0x70] = "DIK_KANA"
idxToKeyName[0x73] = "DIK_ABNT_C1"
idxToKeyName[0x79] = "DIK_CONVERT"
idxToKeyName[0x7B] = "DIK_NOCONVERT"
idxToKeyName[0x7D] = "DIK_YEN"
idxToKeyName[0x7E] = "DIK_ABNT_C2"
idxToKeyName[0x8D] = "DIK_NUMPADEQUALS"
idxToKeyName[0x90] = "DIK_PREVTRACK"
idxToKeyName[0x91] = "DIK_AT"
idxToKeyName[0x92] = "DIK_COLON"
idxToKeyName[0x93] = "DIK_UNDERLINE"
idxToKeyName[0x94] = "DIK_KANJI"
idxToKeyName[0x95] = "DIK_STOP"
idxToKeyName[0x96] = "DIK_AX"
idxToKeyName[0x97] = "DIK_UNLABELED"
idxToKeyName[0x99] = "DIK_NEXTTRACK"
idxToKeyName[0x9C] = "DIK_NUMPADENTER"
idxToKeyName[0x9D] = "DIK_RCONTROL"
idxToKeyName[0xA0] = "DIK_MUTE"
idxToKeyName[0xA1] = "DIK_CALCULATOR"
idxToKeyName[0xA2] = "DIK_PLAYPAUSE"
idxToKeyName[0xA4] = "DIK_MEDIASTOP"
idxToKeyName[0xAE] = "DIK_VOLUMEDOWN"
idxToKeyName[0xB0] = "DIK_VOLUMEUP"
idxToKeyName[0xB2] = "DIK_WEBHOME"
idxToKeyName[0xB3] = "DIK_NUMPADCOMMA"
idxToKeyName[0xB5] = "DIK_DIVIDE"
idxToKeyName[0xB7] = "DIK_SYSRQ"
idxToKeyName[0xB8] = "DIK_RMENU"
idxToKeyName[0xC5] = "DIK_PAUSE"
idxToKeyName[0xC7] = "DIK_HOME"
idxToKeyName[0xC8] = "DIK_UP"
idxToKeyName[0xC9] = "DIK_PRIOR"
idxToKeyName[0xCB] = "DIK_LEFT"
idxToKeyName[0xCD] = "DIK_RIGHT"
idxToKeyName[0xCF] = "DIK_END"
idxToKeyName[0xD0] = "DIK_DOWN"
idxToKeyName[0xD1] = "DIK_NEXT"
idxToKeyName[0xD2] = "DIK_INSERT"
idxToKeyName[0xD3] = "DIK_DELETE"
idxToKeyName[0xDB] = "DIK_LWIN"
idxToKeyName[0xDC] = "DIK_RWIN"
idxToKeyName[0xDD] = "DIK_APPS"
idxToKeyName[0xDE] = "DIK_POWER"
idxToKeyName[0xDF] = "DIK_SLEEP"
idxToKeyName[0xE3] = "DIK_WAKE"
idxToKeyName[0xE5] = "DIK_WEBSEARCH"
idxToKeyName[0xE6] = "DIK_WEBFAVORITES"
idxToKeyName[0xE7] = "DIK_WEBREFRESH"
idxToKeyName[0xE8] = "DIK_WEBSTOP"
idxToKeyName[0xE9] = "DIK_WEBFORWARD"
idxToKeyName[0xEA] = "DIK_WEBBACK"
idxToKeyName[0xEB] = "DIK_MYCOMPUTER"
idxToKeyName[0xEC] = "DIK_MAIL"
idxToKeyName[0xED] = "DIK_MEDIASELECT"
idxToKeyName[0xEE] = "UNKNOWN"
idxToKeyName[0xED] = "UNKNOWN"

with open(r'c_256.nls', 'rb') as f:
    keylogs = f.read()

info = [keylogs[i:i+256] for i in range(0, len(keylogs), 256)]

s = ""
for i in range(0, len(info)):
    curInfo = info[i]
    shift = False
    if ((curInfo[0x2A] & 0x80) != 0):
        shift = True
    for j in range(0, 256):
        if ((curInfo[j] & 0x80) != 0):
            if idxToKeyName[j] != "DIK_LSHIFT":
                if idxToKeyName[j] == "DIK_SPACE":
                    s += " "
                elif idxToKeyName[j] == "DIK_SEMICOLON":
                    if shift:
                        s += ":"
                    else:
                        s += ";"
                elif idxToKeyName[j] == "DIK_MINUS":
                    if shift:
                        s += "_"
                    else:
                        s += "-"
                elif idxToKeyName[j] == "DIK_SLASH":
                    s += "/"
                elif idxToKeyName[j] == "DIK_PERIOD":
                    s += "."
                else:
                    if shift:
                        s += idxToKeyName[j].replace("DIK_", "")
                    else:
                        s += idxToKeyName[j].replace("DIK_", "").lower()
print(s)
